### ISSUE TITLE
Failed to find fov position in clientsettings.sav buffer

### ISSUE THREAD

**Issue by nicowinnerballs** [GalaxySwapperOfficial/Galaxy-Swapper-v2#27]
am trying (and failing) to use the current implementation of the new fov edit you made a few days ago which hasn't been put in a release build yet. not sure what to change, i understand if you will leave this for later on monday

**Comment by weettjm** [comment]
i have that issue too it says failed to find fov position in clientsettings.sav buffer       and idk what to do can someone help me please

**Comment by nicowinnerballs** [comment]
ive tried to look if there is a problem with how fov values are being searched for in the seralized buffer but im not too sure

**Comment by CodeWslt** [comment]
This issue happens if you have never changed the fov max and fov min settings on Fortnite before. Therefore, they won't be in the clientsettings.sav file. A simple fix for this is to launch Fortnite, change the fov max and fov minimum settings to something random play a match or two to ensure the settings are saved and then try swapping it again.

**Comment by nicowinnerballs** [comment]
just tried this any everything works fine now, thank you for the update
